---
- name: Add repository webtatic
  yum: 
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: installed

- name: Install "php{{ php_version }}w"
  yum: 
    name: "{{ item }}"
    state: installed
  with_items:
    - "php{{ php_version }}w-xml"
    - "php{{ php_version }}w-soap"
    - "php{{ php_version }}w-pecl-redis"
    - "php{{ php_version }}w-pdo"
    - "php{{ php_version }}w-opcache"
    - "php{{ php_version }}w-mysql"
    - "php{{ php_version }}w-intl"
    - "php{{ php_version }}w-fpm"
    - "php{{ php_version }}w-gd"
    - "php{{ php_version }}w-bcmath"
    - "php{{ php_version }}w-cli"
    - "php{{ php_version }}w-mbstring"

- name: Update php.ini settings
  lineinfile:
    path: /etc/php.ini
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^;date.timezone", line: "date.timezone = {{ php_timezone }}" }
    - { regexp: "^max_execution_time", line: "max_execution_time = {{ php_max_execution_time }}" }
    - { regexp: "^max_input_time", line: "max_input_time = {{ php_max_input_time }}" }
    - { regexp: "^memory_limit", line: "memory_limit = {{ php_memory_limit }}" }
    - { regexp: "^expose_php", line: "expose_php = {{ php_expose_php }}" }
    - { regexp: "^display_errors", line: "display_errors = {{ php_display_errors }}" }
    - { regexp: "^display_startup_errors", line: "display_startup_errors = {{ php_display_startup_errors }}" }
    - { regexp: "^log_errors", line: "log_errors = {{ php_log_errors }}" }
  

- name: Remove default www pool
  file: 
    path: /etc/php-fpm.d/www.conf
    state: absent

